### ISSUE TITLE
Feature Request: Volumes and PV/C support

### ISSUE THREAD

**Issue by babarinde** [dokku/dokku-scheduler-kubernetes#24]
## Description of problem
On the traditional dokku:storage plugin where users can create and mount volumes on the file system, Persistent Volumes and Claims support will provide similar feature on Kubernetes.
In the dokku:storage plugin, volumes created are shared by all app containers and with the right permissions containers can read and write data from such volumes. However access modes across nodes for PVs vary as seen [here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) and some access modes are only available for specific [PV types](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes):
Suggested UX could be:

- First create a PVC: dokku scheduler-kubernetes:add-pvc $APP_NAME --name PVC_NAME --accessModes "RWX|RWO|ROX " --storage "100" --storageClassName "nfs"
This could create a yml spec

- Create a volume: dokku scheduler-kubernetes:add-volume $APP_NAME --name VOLUME_NAME --pvc|--claimName PVC_NAME

- Mount volume:dokku scheduler-kubernetes:mount $APP_NAME VOLUME_NAME:/container/path
And these two will modify the deployment spec

**Comment by josegonzalez** [comment]
When you create a PVC, should those that take the app name as the first arg, and why? I would imagine the `--name` flag should be the first arg instead.

Should we also have commands for removing PVCs/Volumes? What happens if they are mounted and someone tries to remove them? What is a --claimName vs --pvc?

**Comment by babarinde** [comment]
> When you create a PVC, should those that take the app name as the first arg, and why? I would imagine the --name flag should be the first arg instead.

True, the app name may not even be needed except for some extra metadata since PVCs are not dependent on deployment.

> Should we also have commands for removing PVCs/Volumes? What happens if they are mounted and someone tries to remove them?

Eventually, users will want to remove Volumes, even if it is mounted they are deleted. This might require deleting volumes (as defined in deployment spec) and deleting pvc as 2 separate commands
Please [see protection for storage object](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection)

> What is a --claimName vs --pvc?

As defined in [sample deployment spec](https://gist.github.com/babarinde/7705d48c96bc94c129ffe7b1ca69c123)

--claimName is exactly used particularly when defining a PVC for the volume, i just felt --pvc might an option

I think [this might also be helpful](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#writing-portable-configuration)

**Comment by josegonzalez** [comment]
Should we have commands for listing all of these things as well?

**Comment by babarinde** [comment]
The current k8s manifest might be sufficient for the volume and mounts details. Listing PVCs will be useful before mounting/attaching to deployments

**Comment by babarinde** [comment]
- Create a PVC: 

`dokku scheduler-kubernetes:add-pvc --name $PVC_NAME --access-mode "ReadWriteOnce|ReadOnlyMany|ReadWriteMany " --storage "100" --ns $NAMESPACE  [--storage-class-name "nfs"]`
~since PVC and PV have 1-1 relationship having the $APP_NAME in the mix will help us know that the PVC was used exclusively for that app. (almost all dokku commands refer the $APP_NAME first)~

- Listing a PVC:

`dokku scheduler-kubernetes:list-pvc [$NAMESPACE] `

Deleting a PVC here (Postponed until no longer in active use by any Pods)

`dokku scheduler-kubernetes:remove-pvc --name  $PVC_NAME --ns $NAMESPACE`

- Create and mount volume: 

`dokku scheduler-kubernetes:mount $APP_NAME --name VOLUME_NAME --claim-name $PVC_NAME --path /container/path`

- List mounted volumes: 

`dokku scheduler-kubernetes:list-mount $APP_NAME`

- Unmout a volume

`dokku scheduler-kubernetes:unmount $APP_NAME --name $VOLUME_NAME  --path /container/path --claim-name $PVC_NAME`

- Unmout all volumes

`dokku scheduler-kubernetes:unmount -all $APP_NAME`

**Comment by josegonzalez** [comment]
What happens if you want to use a given PVC with multiple applications? I already have someone asking about that hypothetical use case, and I don't think it's a great idea to make these app-centric.

**Comment by josegonzalez** [comment]
We could potentially allow the ability to inject custom labels into a pvc if we wanted more metatada?

**Comment by babarinde** [comment]
> What happens if you want to use a given PVC with multiple applications?
Sharing PVCs across multiple apps will require the apps to be in the same namespace/project and also use access modes ReadWriteMany and ReadOnlyMany. 

Trying to use a PVC from another namespace should fail, so i felt it would be best practice to have an apps objects in the same namespace

> We could potentially allow the ability to inject custom labels into a pvc if we wanted more metatada?

I guess

**Comment by josegonzalez** [comment]
I think we can definitely check to see if the PVC is in the correct namespace before allowing it to be linked (and fail a deploy if it moves namespaces).

**Comment by babarinde** [comment]
@savant
I've be able to complete the PVC feature, i tested using k8s on Digitalocean, access mode ReadWriteMany using nfs

**Comment by josegonzalez** [comment]
Awesome thanks! I'll take a look at this in the evening, busy with work-related tasks atm. Thanks for the hard work!

**Comment by babarinde** [comment]
closed by #25
