### ISSUE TITLE
scheduler-deploy: properly handle Procfile

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku-scheduler-kubernetes#33]
We currently hardcode the `/start` command. We should only do that for herokuish images, not pack or Dockerfile.

**Comment by babarinde** [comment]
Is this related to issue raised
`# deploy/app-web event: po/retail-app-web-78f686594c-qlqt2 Pulled: Successfully pulled image "xyz.azurecr.io/dokku/app:2" in 30.242504974s`
`# deploy/app-web event: po/app-web-78f686594c-qlqt2 Created: Created container app-web`
`# deploy/app-web event: po/app-web-78f686594c-qlqt2 Failed: Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/start": stat /start: no such file or directory: unknown`
