### ISSUE TITLE
Supporting different ingress controllers

### ISSUE THREAD

**Issue by TobiasBales** [dokku/dokku-scheduler-kubernetes#39]
## Description of problem

I have a k3s cluster running on a couple of raspberry pis - this ships with a traeffik ingress controller (which works nicely for me) - I was wondering if the project would be open to a contribution that adds support for using an "external" (already provisioned) ingress controller to support such use cases.

If so I'd gladly chime in and see if I can make it work.

Thanks for keeping up the great work with dokku and making it scale more! ❤️

**Comment by josegonzalez** [comment]
Sure, I'd be open to an integration with another controller. Feel free to document here how you envision it working first before working on it :)

**Comment by josegonzalez** [comment]
Just a note, [Dokku 0.33.0 comes with k3s support](https://dokku.com/blog/2024/dokku-0.33.0/), and I definitely recommend checking it out. Dokku's kubernetes integration will be performed by the official k3s plugin going forward, and I'll have more plans written up soon :)
