### ISSUE TITLE
Documentation clames this to be the `docker-local` scheduler

### ISSUE THREAD

**Issue by almereyda** [dokku/dokku-scheduler-kubernetes#40]
As I couldn't find the sources for the `docs` repository, I am leaving this here:

In the latest version of the document https://github.com/dokku/docs/blob/2f5e93e94521770c49dc055d540d2d0a92ac67d6/docs/deployment/schedulers/kubernetes/index.html#L2486 it reads *`docker-local` scheduler*, which should probably say *`kubernetes` scheduler* instead?

**Comment by josegonzalez** [comment]
For reference, our documentation has a "pencil" icon near the top-right of each page that will link to the correct repository to edit.
