### ISSUE TITLE
DOKKU_SCALE file does not exist, breaks deploys

### ISSUE THREAD

**Issue by mattmess1221** [dokku/dokku-scheduler-kubernetes#41]
## Description of problem
In Dokku 0.30.1 (fresh install), deployment fails when trying to read from the DOKKU_SCALE file, which doesn't exist. Manually creating the file with the contents `web=1` will allow it to deploy.

```
-----> Deploying testapp via the kubernetes scheduler...
=====> Deploying via kubernetes
/var/lib/dokku/plugins/enabled/scheduler-kubernetes/scheduler-deploy: line 8: /home/dokku/testapp/DOKKU_SCALE: No such file or directory
=====> Deploy complete
```

### How reproducible
Every deployment will fail, but report as deployed.

### Steps to Reproduce

1. Deploy an app to kubernetes

### `dokku report testapp` output
<details>
<pre>
-----> uname: Linux 352bf3f0c877 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           3789         559         349          24        2879        2922
       Swap:             0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           23.0.1
        API version:       1.42
        Go version:        go1.19.5
        Git commit:        a5ee5b1
        Built:             Thu Feb  9 19:46:56 2023
        OS/Arch:           linux/amd64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          23.0.1
         API version:      1.42 (minimum version 1.12)
         Go version:       go1.19.5
         Git commit:       bc3805a
         Built:            Thu Feb  9 19:48:42 2023
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.18
         GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
        runc:
         Version:          1.1.4
         GitCommit:        v1.1.4-0-g5fd4c4d
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         compose: Docker Compose (Docker Inc.)
           Version:  v2.16.0
           Path:     /usr/libexec/docker/cli-plugins/docker-compose

       Server:
        Containers: 4
         Running: 3
         Paused: 0
         Stopped: 1
        Images: 39
        Server Version: 23.0.1
        Storage Driver: overlay2
         Backing Filesystem: xfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
        runc version: v1.1.4-0-g5fd4c4d
        init version: de40ad0
        Security Options:
         seccomp
          Profile: builtin
        Kernel Version: 3.10.0-1160.88.1.el7.x86_64
        Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 3.7GiB
        Name: snip
        ID: 3LFL:4GSO:N7AX:Q4UF:5RKM:W725:K5QT:CTSB:ZJMV:XKOM:U4GN:SDXY
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Experimental: false
        Insecure Registries:
         10.193.196.185:5000
         127.0.0.0/8
        Registry Mirrors:
         snip
        Live Restore Enabled: false

-----> git version: git version 2.25.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version:
       herokuish: v0.5.40
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v244
         heroku-buildpack-nodejs    v202
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v223
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v38
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v227
         heroku-buildpack-go        v169
         heroku-buildpack-nginx     v22
         buildpack-null             v3
-----> dokku version: dokku version 0.30.1
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins:
         00_dokku-standard    0.30.1 enabled    dokku core standard plugin
         20_events            0.30.1 enabled    dokku core events logging plugin
         app-json             0.30.1 enabled    dokku core app-json plugin
         apps                 0.30.1 enabled    dokku core apps plugin
         builder              0.30.1 enabled    dokku core builder plugin
         builder-dockerfile   0.30.1 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.30.1 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.30.1 enabled    dokku core builder-lambda plugin
         builder-null         0.30.1 enabled    dokku core builder-null plugin
         builder-pack         0.30.1 enabled    dokku core builder-pack plugin
         buildpacks           0.30.1 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.30.1 enabled    dokku core caddy-vhosts plugin
         certs                0.30.1 enabled    dokku core certificate management plugin
         checks               0.30.1 enabled    dokku core checks plugin
         common               0.30.1 enabled    dokku core common plugin
         config               0.30.1 enabled    dokku core config plugin
         cron                 0.30.1 enabled    dokku core cron plugin
         docker-options       0.30.1 enabled    dokku core docker-options plugin
         domains              0.30.1 enabled    dokku core domains plugin
         enter                0.30.1 enabled    dokku core enter plugin
         git                  0.30.1 enabled    dokku core git plugin
         haproxy-vhosts       0.30.1 enabled    dokku core haproxy-vhosts plugin
         logs                 0.30.1 enabled    dokku core logs plugin
         network              0.30.1 enabled    dokku core network plugin
         nginx-vhosts         0.30.1 enabled    dokku core nginx-vhosts plugin
         plugin               0.30.1 enabled    dokku core plugin plugin
         postgres             1.32.0 enabled    dokku postgres service plugin
         proxy                0.30.1 enabled    dokku core proxy plugin
         ps                   0.30.1 enabled    dokku core ps plugin
         redis                1.32.0 enabled    dokku redis service plugin
         registry             0.30.1 enabled    dokku core registry plugin
         repo                 0.30.1 enabled    dokku core repo plugin
         resource             0.30.1 enabled    dokku core resource plugin
         run                  0.30.1 enabled    dokku core run plugin
         scheduler            0.30.1 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.30.1 enabled    dokku core scheduler-docker-local plugin
         scheduler-kubernetes 0.20.1 enabled    dokku scheduler-kubernetes plugin
         scheduler-null       0.30.1 enabled    dokku core scheduler-null plugin
         shell                0.30.1 enabled    dokku core shell plugin
         ssh-keys             0.30.1 enabled    dokku core ssh-keys plugin
         storage              0.30.1 enabled    dokku core storage plugin
         trace                0.30.1 enabled    dokku core trace plugin
         traefik-vhosts       0.30.1 enabled    dokku core traefik-vhosts plugin
=====> testapp app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> testapp app information
       App created at:                1679059473
       App deploy source:             testapp
       App deploy source metadata:    testapp
       App dir:                       /home/dokku/testapp
       App locked:                    false
=====> testapp builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> testapp builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> testapp builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> testapp builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> testapp buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> testapp ssl information
       Ssl dir:                       /home/dokku/testapp/tls
       Ssl enabled:                   false
       Ssl hostnames:
       Ssl expires at:
       Ssl issuer:
       Ssl starts at:
       Ssl subject:
       Ssl verified:
=====> testapp checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> testapp cron information
       Cron task count:               0
=====> testapp docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10
       Docker options run:
=====> testapp domains information
       Domains app enabled:           true
       Domains app vhosts:            testapp.snip
       Domains global enabled:        true
       Domains global vhosts:         snip
=====> testapp git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       18a94a7
       Git source image:
       Git last updated at:           1679061470
=====> testapp logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> testapp network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                158.26.0.6:5000
=====> testapp nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/testapp-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/testapp-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx nginx conf sigil path:
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> testapp proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000
       Proxy type:                    nginx-ingress
=====> testapp ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
=====> testapp registry information
       Registry computed image repo:      dokku/testapp
       Registry computed push on release: true
       Registry computed server:          snip
       Registry global push on release:   true
       Registry global server:            snip
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:              6
=====> testapp resource information
=====> testapp scheduler information
       Scheduler computed selected:   kubernetes
       Scheduler global selected:     docker-local
       Scheduler selected:            kubernetes
=====> testapp scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> testapp scheduler-kubernetes information
       Scheduler kubernetes cert manager enabled:
       Scheduler kubernetes imagePullSecrets:
       Scheduler kubernetes ingress enabled: false
       Scheduler kubernetes namespace: testapp
       Scheduler kubernetes pod max unavailable:
       Scheduler kubernetes pod min available:
       Scheduler kubernetes service process types: http
=====> testapp storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:
</pre>
</details>

### How (deb/make) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
It was installed on a RHEL 7 VM with Docker

```
#!/usr/bin/env bash

DOKKU_VERSION=0.30.1

docker pull "dokku/dokku:$DOKKU_VERSION"

pathenv=$(docker inspect "dokku/dokku:$DOKKU_VERSION" --format 'json' | jq '.[0].Config.Env | map(index("=") as $ix | {(.[:$ix]) : .[$ix+1:]}) | add')
docker container run \
    --env DOKKU_HOSTNAME=dokku.me \
    --env DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku \
    --env DOKKU_LIB_HOST_ROOT=/var/lib/dokku/var/lib/dokku \
    --env PATH="$pathenv:/var/lib/dokku/data/scheduler-kubernetes" \
    --name dokku \
    --publish 3022:22 \
    --publish 8080:80 \
    --publish 8443:443 \
    --volume /var/lib/dokku:/mnt/dokku \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --rm \
    --detach \
    "dokku/dokku:$DOKKU_VERSION"
```

**Comment by mattmess1221** [comment]
Simple fix is to change this line

https://github.com/dokku/dokku-scheduler-kubernetes/blob/814aeee7f1230fcf552098212f00a6bc0fd0d5ff/scheduler-deploy#L89

```diff
diff --git a/scheduler-deploy b/scheduler-deploy
index c565604..123de21 100755
--- a/scheduler-deploy
+++ b/scheduler-deploy
@@ -86,7 +86,7 @@ scheduler-kubernetes-scheduler-deploy() {
     fi

     plugn trigger post-deploy-kubernetes-apply "$APP" "$PROC_TYPE" "$TMP_FILE" deployment
-  done <"$DOKKU_SCALE_FILE"
+  done < <(plugn trigger ps-current-scale "$APP")

   dokku_log_info2 "Deploy complete"
```

**Comment by josegonzalez** [comment]
Mind creating an MR @killjoy1221 ?
